### ISSUE TITLE
#WPfeedback and Feature Requests

### ISSUE THREAD

**Issue by heyjoecampbell** [artstorm/wp-humans-txt#20]
Here are a few suggestions that could make your plugin even more awesome:

- add settings link - http://i.imgur.com/nnRvk4w.png
- add line break for New Base Template insertion - http://i.imgur.com/CnvPqpL.png
- move "View humans.txt" button next to "New Base Template" button
- open humans.txt link in new window
- provide a list of all usable shortcodes [lastpostdate]

**Comment by artstorm** [comment]
🧹 Cleaning up old repos.
